### ISSUE TITLE
Article ID missing

### ISSUE THREAD

**Issue by SamuelKupferschmid** [aeshirey/WikipediaProcessing#2]
Hy Adam,

This library does a good job in loading and parsing wiki dumps quickly.
Unfortunately it only loads Text and Title of an article.
It would be great if the ID of articles would also be extracted. As it is often used as reference in other parts. 
What's your opinion? If you like I could create a PR as it is almost a one liner.

**Comment by aeshirey** [comment]
Sounds like a good idea! Feel free to create a PR and I'll check it out
when available.

**Comment by aeshirey** [comment]
Closed with PR #3
